baseurl: /MCSS
pygments: true
markdown: redcarpet
safe: true

project-name: MCSS
project-url: http://github.com/operatino/MCSS
project-descr-url: http://github.com/operatino/MCSS#%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE%D1%81%D0%BB%D0%BE%D0%B9%D0%BD%D1%8B%D0%B9-css

cssg-author-title: Css-o-Gram
cssg-author-name: <a href="mailto:eugeny.horoshilov@odnoklassniki.ru">Евгений Хорошилов</a>

res-project-author: <a href="http://rhr.me">Роберт Харитонов</a>
res-project-author-twitter: <a href="http://twitter.com/operatino">@operatino</a>

res-watch-on-github: Посмотреть проект на
res-download-archive: Скачать в архиве
res-footer: Сайт опубликован с помощью <a href="http://pages.github.com">GitHub Pages</a> на основе <a href="http://jekyllrb.com">Jekyll</a>
res-author: Автор проекта

res-navigation: Навигация
res-navigation-modules: Модули документации
res-navigation-links: Ссылки


en-baseurl: /MCSS/en

en-project-url: http://github.com/operatino/MCSS/en
en-project-descr-url: http://github.com/operatino/MCSS/blob/gh-pages/en/README.md

en-cssg-author-title: Css-o-Gram
en-cssg-author-name: <a href="mailto:eugeny.horoshilov@odnoklassniki.ru">Evgeny Khoroshilov</a>

en-res-project-author: <a href="http://rhr.me">Robert Haritonov</a>
en-res-project-author-twitter: <a href="http://twitter.com/operatino_en">@operatino</a>

en-res-watch-on-github: Checkout project at
en-res-download-archive: Download archive
en-res-footer: This site is published through <a href="http://pages.github.com">GitHub Pages</a> based on <a href="http://jekyllrb.com">Jekyll</a>
en-res-author: Project author

en-res-navigation: Navigation
en-res-navigation-modules: Documentation modules
en-res-navigation-links: Links


ja-baseurl: /MCSS/ja

ja-project-url: http://github.com/operatino/MCSS/ja
ja-project-descr-url: http://github.com/operatino/MCSS/blob/gh-pages/ja/README.md

ja-cssg-author-title: Css-o-Gram
ja-cssg-author-name: <a href="mailto:eugeny.horoshilov@odnoklassniki.ru">Evgeny Khoroshilov</a>

ja-res-project-author: <a href="http://rhr.me">Robert Haritonov</a>
ja-res-project-author-twitter: <a href="http://twitter.com/operatino_en">@operatino</a>

ja-res-watch-on-github: Checkout project at
ja-res-download-archive: Download archive
ja-res-footer: This site is published through <a href="http://pages.github.com">GitHub Pages</a> based on <a href="http://jekyllrb.com">Jekyll</a>
ja-res-author: Project author

ja-res-navigation: ナビゲーション
ja-res-navigation-modules: ドキュメントモジュール
ja-res-navigation-links: リンク